version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "gomyway1216"
      - "carolina-museum"
    versioning-strategy: "increase"
